package com.idevsu.mythos

import android.app.Activity
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.view.Gravity
import android.view.View
import android.widget.*
import org.json.JSONArray
import org.json.JSONObject

class MythosUi(private val a: Activity, private val data: JSONObject, private val prefs: android.content.SharedPreferences) {
    private var xp = prefs.getInt("xp", 0)
    private val cyan=Color.rgb(0,230,255); private val green=Color.rgb(0,255,145); private val gold=Color.rgb(255,195,40)
    private val orange=Color.rgb(255,100,55); private val blue=Color.rgb(55,150,255); private val bg=Color.rgb(5,9,18); private val panel=Color.rgb(15,24,40); private val muted=Color.rgb(105,125,150)
    private fun t(s:String,z:Float=15f,c:Int=Color.WHITE)=TextView(a).apply{text=s;textSize=z;setTextColor(c);setPadding(12,7,12,7);typeface=Typeface.MONOSPACE}
    private fun card():LinearLayout=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL;setPadding(12,10,12,10);background=GradientDrawable().apply{cornerRadius=22f;setColor(panel);setStroke(1,Color.rgb(30,48,70))};elevation=3f}
    private fun b(s:String,c:Int=cyan,f:()->Unit)=Button(a).apply{text=s;textSize=13f;typeface=Typeface.create(Typeface.MONOSPACE,Typeface.BOLD);setTextColor(Color.WHITE);background=GradientDrawable().apply{cornerRadius=18f;setColor(Color.rgb(8,20,34));setStroke(2,c)};setPadding(8,8,8,8);setOnClickListener{f()}}
    private fun root()=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL;setPadding(18,12,18,12);setBackgroundColor(bg)}
    private fun set(r:LinearLayout){val f=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL;addView(ScrollView(a).apply{setBackgroundColor(bg);addView(r)},LinearLayout.LayoutParams(-1,0,1f));addView(nav())};a.setContentView(f)}
    private fun nav()=LinearLayout(a).apply{orientation=LinearLayout.HORIZONTAL;setPadding(2,5,2,2);background=GradientDrawable().apply{setColor(Color.rgb(8,14,25));setStroke(1,Color.rgb(25,42,62))};listOf("⌂\nHOME" to {home()},"⌁\nMAP" to {map()},"▤\nCODEX" to {codex()},"▥\nLOGS" to {logs()},"●\nPROFILE" to {profile()}).forEach{(s,f)->addView(TextView(a).apply{text=s;gravity=Gravity.CENTER;textSize=10f;setTextColor(muted);setPadding(4,5,4,5);setOnClickListener{f()}},LinearLayout.LayoutParams(0,-2,1f))}}
    fun home(){val r=root();r.addView(t("△  MYTHOS",31f,cyan).apply{gravity=Gravity.CENTER;typeface=Typeface.DEFAULT_BOLD});r.addView(t("HACK THE WORLD",18f).apply{gravity=Gravity.CENTER});r.addView(t("> SYSTEM STATUS: ONLINE  ▮",12f,green).apply{gravity=Gravity.CENTER});r.addView(t("KERNEL_VERSION: TPS_v1.0  |  INSTALLATION: ${pct()}%",10f,muted).apply{gravity=Gravity.CENTER})
        val x=card();x.addView(t("ZERO LAG                                  $xp XP",17f,green));val p=ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);p.max=10000;p.progress=xp.coerceAtMost(10000);x.addView(p);x.addView(t("LVL ${level()}   →   ${500-(xp%500)} XP to next level",11f,muted));r.addView(x,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,10,0,10)})
        r.addView(t("> SYSTEM MODULES",13f,muted));val ss=data.getJSONArray("sections");val cs=listOf(cyan,green,gold,orange,blue,cyan,gold);val icons=listOf("⚡","🔎","⚙","🔓","◈","↻","▤")
        for(i in 0 until ss.length()){val s=ss.getJSONObject(i);val id=s.getString("id");val c=card();val row=LinearLayout(a).apply{gravity=Gravity.CENTER_VERTICAL};row.addView(t(icons[i%7],25f,cs[i%7]),LinearLayout.LayoutParams(45,-2));val m=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL;addView(t(s.getString("title"),16f,cs[i%7]));addView(t(sub(id),11f,muted))};row.addView(m,LinearLayout.LayoutParams(0,-2,1f));row.addView(t(progress(id),12f,muted));c.addView(row);c.setOnClickListener{if(unlocked(id))entries(s.getString("title"),s.getJSONArray("types"),id)else Toast.makeText(a,"LOCKED • complete previous module",Toast.LENGTH_SHORT).show()};r.addView(c,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,5,0,0)})}
        r.addView(t("> QUICK ACCESS",13f,muted));val q=LinearLayout(a);q.orientation=LinearLayout.HORIZONTAL;listOf("▤\nCODEX" to {codex()},"◈\nMAP" to {map()},"▥\nLOGS" to {logs()},"●\nPROFILE" to {profile()}).forEach{(s,f)->q.addView(b(s,cyan,f),LinearLayout.LayoutParams(0,75,1f).apply{setMargins(2,2,2,2)})};r.addView(q);val l=card();l.addView(t("◉  LATEST SIGNAL",12f,green));l.addView(t("The Silicon Sutra",20f));l.addView(t("Explore the convergence of ancient wisdom, computation, and the MythOS kernel.",12f,muted));r.addView(l);set(r)}
    private fun entries(title:String,types:JSONArray,id:String){val r=root();r.addView(t(title,25f,cyan));r.addView(t(brief(id),12f,muted));val es=data.getJSONArray("entries");for(i in 0 until es.length()){val e=es.getJSONObject(i);if(has(types,e.getString("type"))){val c=card();c.addView(t((if(done(e.getString("id")))"✓  "else"◇  ")+e.getString("title")+"   +"+e.getInt("xp")+" XP",15f,if(done(e.getString("id")))green else Color.WHITE));c.addView(t(e.getString("source")+" • "+e.getInt("words")+" words",10f,muted));c.setOnClickListener{read(e,id)};r.addView(c,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,5,0,0)})}};r.addView(b("← HOME",blue){home()});set(r)}
    private fun read(e:JSONObject,id:String){val r=root();r.addView(t(e.getString("title"),24f,cyan));r.addView(t(e.getString("source")+" • "+e.getInt("words")+" words • "+e.getInt("xp")+" XP",10f,muted));val cs=e.getJSONArray("concepts");if(cs.length()>0)r.addView(t("SIGNALS • "+join(cs),10f,cyan));val c=card();val body=a.assets.open("corpus/"+e.getString("source")).bufferedReader().use{it.readText()};c.addView(t(body,15f,Color.rgb(220,230,240)));r.addView(c,LinearLayout.LayoutParams(-1,0,1f).apply{setMargins(0,8,0,8)});if(done(e.getString("id")))r.addView(t("✓ NODE SYNCHRONIZED",13f,green))else r.addView(b("SYNC NODE  +${e.getInt("xp")} XP",green){award(e);if(e.getString("type")=="checkpoint")checkpoint(e,id)else entries(id.uppercase(),find(id)!!.getJSONArray("types"),id)});r.addView(b("← BACK",blue){entries(id.uppercase(),find(id)!!.getJSONArray("types"),id)});set(r)}
    private fun checkpoint(e:JSONObject,id:String){val r=root();r.addView(t("◉ CHECKPOINT",24f,green));r.addView(t(e.getString("title"),18f));r.addView(t("SYSTEM COMPREHENSION • prove you traversed the node",12f,muted));val cs=e.getJSONArray("concepts");val ans=if(cs.length()>0)cs.getString(0)else e.getString("title").split(" ")[0];val input=EditText(a).apply{hint="enter a signal";setTextColor(Color.WHITE);setHintTextColor(muted)};r.addView(input);r.addView(b("SUBMIT CHECKPOINT",green){if(input.text.toString().trim().equals(ans,true)){xp+=75;prefs.edit().putInt("xp",xp).putBoolean("cp_"+e.getString("id"),true).apply();Toast.makeText(a,"CHECKPOINT PASSED +75 XP",Toast.LENGTH_SHORT).show();entries(id.uppercase(),find(id)!!.getJSONArray("types"),id)}else Toast.makeText(a,"RE-READ THE NODE",Toast.LENGTH_SHORT).show()});set(r)}
    private fun map(){val r=root();r.addView(t("WORLD MAP",25f,cyan));r.addView(t("NAVIGATE THE KNOWLEDGE GRAPH",11f,muted));r.addView(t("\n      ◌──────△──────◌\n     /       │       \\\n  SOCIETY   CORE    PHYSICS\n     \\       │       /\n      ◌──────◇──────◌\n\n CONSCIOUSNESS • TECHNOLOGY • SYSTEMS • FREEDOM",16f,cyan));val g=data.getJSONObject("graph");val c=card();c.addView(t("EXPLORATION PROGRESS",11f,muted));c.addView(t("${completed()} / ${data.getJSONObject("corpus").getInt("file_count")} NODES",22f,green));c.addView(t("${pct()}% synchronized • ${g.getJSONArray("nodes").length()} nodes • ${g.getJSONArray("edges").length()} links",11f,Color.WHITE));r.addView(c);set(r)}
    private fun codex(){val r=root();r.addView(t("LEXICON",25f,cyan));r.addView(t("DISCOVERED KNOWLEDGE SIGNALS",11f,muted));val n=data.getJSONObject("graph").getJSONArray("nodes");for(i in 0 until n.length()){val x=n.getJSONObject(i);if(x.getString("type")=="concept"){val c=card();c.addView(t("◇  "+x.getString("label"),14f,cyan));r.addView(c,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,4,0,0)})}};set(r)}
    private fun logs(){val r=root();r.addView(t("DEV LOGS",25f,cyan));r.addView(t("JOURNAL OF PROGRESS",11f,muted));val es=data.getJSONArray("entries");for(i in es.length()-1 downTo 0){val e=es.getJSONObject(i);if(e.getString("type")=="checkpoint"||e.getString("type")=="orientation"){val c=card();c.addView(t(e.getString("title")+"   +"+e.getInt("xp")+" XP",14f,green));c.addView(t(e.getString("source")+" • "+(if(done(e.getString("id")))"SYNCHRONIZED"else"DISCOVERED"),10f,muted));r.addView(c,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,4,0,0)})}};set(r)}
    private fun profile(){val r=root();r.addView(t("OPERATOR PROFILE",25f,cyan));r.addView(t("MYTHOS INSTALLATION STATE",11f,muted));val c=card();c.addView(t("◢  ZERO LAG",22f,cyan));c.addView(t("LEVEL ${level()}",18f));c.addView(t("$xp XP",16f,green));c.addView(t("${completed()} / ${data.getJSONObject("corpus").getInt("file_count")} NODES\n${data.getJSONObject("graph").getJSONArray("nodes").length()} KNOWLEDGE NODES\nINSTALLATION ${pct()}%",12f,muted));r.addView(c);r.addView(t("ACHIEVEMENTS",14f,gold));listOf("🏆 FIRST BOOT","🏆 DIAGNOSTIC","🏆 EXPLORER","🏆 KNOWLEDGE SEEKER").forEach{val x=card();x.addView(t(it,13f,gold));r.addView(x,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,4,0,0)})};set(r)}
    private fun done(id:String)=prefs.getBoolean("done_"+id,false);private fun award(e:JSONObject){if(done(e.getString("id")))return;xp+=e.getInt("xp");prefs.edit().putBoolean("done_"+e.getString("id"),true).putInt("xp",xp).apply()};private fun has(a:JSONArray,v:String)= (0 until a.length()).any{a.getString(it)==v};private fun find(id:String):JSONObject?{val a=data.getJSONArray("sections");for(i in 0 until a.length())if(a.getJSONObject(i).getString("id")==id)return a.getJSONObject(i);return null};private fun unlocked(id:String):Boolean{val o=listOf("boot","diagnostic","firewall","overclock","defrag","reboot","codex");val i=o.indexOf(id);return i<=0||complete(o[i-1])};private fun complete(id:String):Boolean{val s=find(id)?:return false;val es=data.getJSONArray("entries");var n=0;var d=0;for(i in 0 until es.length()){val e=es.getJSONObject(i);if(has(s.getJSONArray("types"),e.getString("type"))){n++;if(done(e.getString("id")))d++}};return n>0&&n==d};private fun progress(id:String):String{val s=find(id)?:return"0/0";val es=data.getJSONArray("entries");var n=0;var d=0;for(i in 0 until es.length()){val e=es.getJSONObject(i);if(has(s.getJSONArray("types"),e.getString("type"))){n++;if(done(e.getString("id")))d++}};return"$d/$n"};private fun completed():Int{val es=data.getJSONArray("entries");return(0 until es.length()).count{done(es.getJSONObject(it).getString("id"))}};private fun pct()=if(data.getJSONObject("corpus").getInt("file_count")==0)0 else completed()*100/data.getJSONObject("corpus").getInt("file_count");private fun level()=1+xp/500;private fun join(a:JSONArray)= (0 until a.length()).joinToString(" • "){a.getString(it)};private fun sub(id:String)=when(id){"boot"->"Boot Sequence";"diagnostic"->"System Analysis";"firewall"->"Execution";"overclock"->"Optimization";"defrag"->"Integration";"reboot"->"Reconstruction";else->"Deep Archive"};private fun brief(id:String)=when(id){"boot"->"Initialize • awareness → system boot → first signal";"diagnostic"->"Analyze • observe the system before changing it";"firewall"->"Execute • cross from theory into system mechanics";"overclock"->"Optimize • increase throughput and discover connections";"defrag"->"Integrate • assemble scattered knowledge into one model";"reboot"->"Synchronize • re-enter with a changed perspective";else->"Explore • the deep archive behind the installation"}
}
